services:
  n8n:
    image: n8nio/n8n
    ports:
      - "${N8N_PORT}:5678"
    volumes:
      - ./n8n-data:/home/node/.n8n
      - ./documents:/home/node/.n8n-files/documents

  qdrant:
    image: qdrant/qdrant
    ports:
      - "${QDRANT_PORT}:6333"
    volumes:
      - ./qdrant-data:/qdrant/storage

  ollama:
    image: ollama/ollama
    ports:
      - "${OLLAMA_PORT}:11434"
    volumes:
      - ./ollama-data:/root/.ollama
